#!/usr/bin/env node
const express = require('express');
function normalizePort(val) {
    let port = parseInt(val, 10);
    if (isNaN(port)) {
        // named pipe
        return val;
    }
    if (port >= 0) {
        // port number
        return port;
    }
    return false;
}

let app = express();
app.use(express.static('./html'));
let server = app.listen(3000);
let port = normalizePort(3000);
server.on('error', function (error) {
    if (error.syscall !== 'listen') {
        throw error;
    }
    let bind = typeof port === 'string'
        ? 'Pipe ' + port
        : 'Port ' + port;
    switch (error.code) {
        case 'EACCES':
            console.error(bind + ' requires elevated privileges');
            // process.exit(1);
            msgArr.push({ port, msg: 'requires elevated privileges' })
            break;
        case 'EADDRINUSE':
            console.error(bind + ' is already in use');
            // process.exit(1); //结束进程
            msgArr.push({ port, msg: bind + ' is already in use' })
            break;
        default:
            throw error;
    }
});
server.on('listening', function () {
    let addr = server.address();
    let bind = typeof addr === 'string'
        ? 'pipe ' + addr
        : 'port ' + addr.port;
    console.log('服务已开启，请在浏览器中打开 ' + bind + ' 端口，完成最后的初始化配置。');
});
